// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewPost struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type Post struct {
	ID              string `json:"id"`
	ContentText     string `json:"contentText"`
	PublicationDate int    `json:"publicationDate"`
	UserID          string `json:"userId"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
