// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewPost struct {
	Text   string `json:"text"`
	UserID int64  `json:"userId"`
}

type Post struct {
	ID              int64  `json:"id"`
	ContentText     string `json:"contentText"`
	PublicationDate int64  `json:"publicationDate"`
	UserID          int64  `json:"userId"`
}

type User struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}
